/**
 * {{appName}} - Chat Agent Template
 *
 * Auto-generated by LiquidOS Builder. Connects to an A2A executor
 * for conversational AI interactions.
 */

import { useState, useRef, useCallback } from 'react';
import { Bot, Send, Loader2, User } from 'lucide-react';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
}

const A2A_ENDPOINT = '/a2a';

export default function App() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  const sendMessage = useCallback(async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: Message = {
      id: crypto.randomUUID(),
      role: 'user',
      content: input.trim(),
      timestamp: Date.now(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);

    try {
      const res = await fetch(A2A_ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          jsonrpc: '2.0',
          method: 'message/send',
          id: userMessage.id,
          params: {
            message: {
              role: 'user',
              parts: [{ kind: 'text', text: userMessage.content }],
            },
          },
        }),
      });

      const data = await res.json();
      const responseText = data?.result?.artifacts?.[0]?.parts?.[0]?.text
        || data?.result?.status?.message?.parts?.[0]?.text
        || 'No response received.';

      setMessages(prev => [...prev, {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: responseText,
        timestamp: Date.now(),
      }]);
    } catch (err) {
      setMessages(prev => [...prev, {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: `Error: ${err instanceof Error ? err.message : 'Failed to send message'}`,
        timestamp: Date.now(),
      }]);
    } finally {
      setIsLoading(false);
      scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
    }
  }, [input, isLoading]);

  return (
    <div className="flex flex-col h-full bg-glass-background">
      {/* Header */}
      <header className="flex items-center gap-3 px-4 py-3 border-b border-white/10">
        <Bot size={20} className="text-accent" />
        <h1 className="text-sm font-semibold text-primary">{'{{appName}}'}</h1>
      </header>

      {/* Messages */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto p-4 space-y-3">
        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center h-full text-center">
            <Bot size={32} className="text-secondary/30 mb-3" />
            <p className="text-xs text-secondary">Start a conversation with the AI assistant.</p>
          </div>
        )}
        {messages.map(msg => (
          <div
            key={msg.id}
            className={`flex gap-2 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
          >
            {msg.role === 'assistant' && (
              <div className="w-6 h-6 rounded-full bg-accent/20 flex items-center justify-center flex-shrink-0 mt-1">
                <Bot size={12} className="text-accent" />
              </div>
            )}
            <div
              className={`max-w-[80%] p-3 rounded-xl text-xs ${
                msg.role === 'user'
                  ? 'bg-accent/20 border border-accent/30 text-primary'
                  : 'bg-white/5 border border-white/10 text-primary/90'
              }`}
            >
              {msg.content}
            </div>
            {msg.role === 'user' && (
              <div className="w-6 h-6 rounded-full bg-white/10 flex items-center justify-center flex-shrink-0 mt-1">
                <User size={12} className="text-secondary" />
              </div>
            )}
          </div>
        ))}
        {isLoading && (
          <div className="flex gap-2">
            <div className="w-6 h-6 rounded-full bg-accent/20 flex items-center justify-center">
              <Loader2 size={12} className="text-accent animate-spin" />
            </div>
            <div className="p-3 rounded-xl bg-white/5 border border-white/10">
              <div className="flex gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-secondary/50 animate-bounce" />
                <span className="w-1.5 h-1.5 rounded-full bg-secondary/50 animate-bounce delay-100" />
                <span className="w-1.5 h-1.5 rounded-full bg-secondary/50 animate-bounce delay-200" />
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Input */}
      <div className="flex gap-2 p-4 border-t border-white/10">
        <input
          type="text"
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && sendMessage()}
          placeholder="Type a message..."
          disabled={isLoading}
          className="flex-1 px-3 py-2 text-xs rounded-lg bg-white/5 border border-white/10 text-primary placeholder:text-secondary/50 focus:outline-none focus:border-accent/50 disabled:opacity-50"
        />
        <button
          onClick={sendMessage}
          disabled={isLoading || !input.trim()}
          className="p-2 rounded-lg bg-accent/20 text-accent hover:bg-accent/30 disabled:opacity-50 transition-colors"
        >
          {isLoading ? <Loader2 size={16} className="animate-spin" /> : <Send size={16} />}
        </button>
      </div>
    </div>
  );
}
