/**
 * {{appName}} - Data Viewer Template
 *
 * Auto-generated by LiquidOS Builder. Replace sample columns and data
 * with real data sources and customize the table layout.
 */

import { useState, useMemo } from 'react';
import { Table2, Search, ChevronLeft, ChevronRight, ArrowUpDown } from 'lucide-react';

interface Column {
  key: string;
  label: string;
  sortable?: boolean;
}

interface DataRow {
  id: string;
  [key: string]: string | number;
}

const COLUMNS: Column[] = [
  { key: 'name', label: 'Name', sortable: true },
  { key: 'status', label: 'Status', sortable: true },
  { key: 'value', label: 'Value', sortable: true },
  { key: 'updated', label: 'Updated', sortable: true },
];

const SAMPLE_DATA: DataRow[] = Array.from({ length: 25 }, (_, i) => ({
  id: `row-${i + 1}`,
  name: `Item ${i + 1}`,
  status: ['Active', 'Pending', 'Complete'][i % 3],
  value: Math.floor(Math.random() * 1000),
  updated: new Date(Date.now() - i * 86400000).toLocaleDateString(),
}));

const PAGE_SIZE = 10;

export default function App() {
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(0);
  const [sortKey, setSortKey] = useState<string | null>(null);
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');

  const filtered = useMemo(() => {
    let data = SAMPLE_DATA;
    if (search) {
      const q = search.toLowerCase();
      data = data.filter(row =>
        Object.values(row).some(v => String(v).toLowerCase().includes(q))
      );
    }
    if (sortKey) {
      data = [...data].sort((a, b) => {
        const av = a[sortKey], bv = b[sortKey];
        const cmp = av < bv ? -1 : av > bv ? 1 : 0;
        return sortDir === 'asc' ? cmp : -cmp;
      });
    }
    return data;
  }, [search, sortKey, sortDir]);

  const totalPages = Math.ceil(filtered.length / PAGE_SIZE);
  const pageData = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

  const handleSort = (key: string) => {
    if (sortKey === key) {
      setSortDir(prev => prev === 'asc' ? 'desc' : 'asc');
    } else {
      setSortKey(key);
      setSortDir('asc');
    }
  };

  return (
    <div className="flex flex-col h-full bg-glass-background">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-4 border-b border-white/10">
        <div className="flex items-center gap-3">
          <Table2 size={20} className="text-accent" />
          <h1 className="text-sm font-semibold text-primary">{'{{appName}}'}</h1>
        </div>
        <span className="text-xs text-secondary">{filtered.length} items</span>
      </header>

      {/* Search */}
      <div className="px-6 py-3">
        <div className="relative">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-secondary/50" />
          <input
            type="text"
            value={search}
            onChange={e => { setSearch(e.target.value); setPage(0); }}
            placeholder="Search..."
            className="w-full pl-8 pr-3 py-2 text-xs rounded-lg bg-white/5 border border-white/10 text-primary placeholder:text-secondary/50 focus:outline-none focus:border-accent/50"
          />
        </div>
      </div>

      {/* Table */}
      <div className="flex-1 overflow-auto px-6">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-white/10">
              {COLUMNS.map(col => (
                <th
                  key={col.key}
                  className="text-left py-2 px-3 text-secondary font-medium"
                >
                  {col.sortable ? (
                    <button
                      onClick={() => handleSort(col.key)}
                      className="flex items-center gap-1 hover:text-primary transition-colors"
                    >
                      {col.label}
                      <ArrowUpDown size={10} className={sortKey === col.key ? 'text-accent' : ''} />
                    </button>
                  ) : col.label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {pageData.map(row => (
              <tr key={row.id} className="border-b border-white/5 hover:bg-white/5 transition-colors">
                {COLUMNS.map(col => (
                  <td key={col.key} className="py-2 px-3 text-primary/80">
                    {col.key === 'status' ? (
                      <span className={`px-2 py-0.5 rounded text-[10px] font-medium ${
                        row[col.key] === 'Active' ? 'bg-emerald-500/20 text-emerald-400' :
                        row[col.key] === 'Pending' ? 'bg-amber-500/20 text-amber-400' :
                        'bg-white/10 text-secondary'
                      }`}>
                        {row[col.key]}
                      </span>
                    ) : (
                      String(row[col.key])
                    )}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      <div className="flex items-center justify-between px-6 py-3 border-t border-white/10">
        <span className="text-xs text-secondary">
          Page {page + 1} of {totalPages || 1}
        </span>
        <div className="flex gap-1">
          <button
            onClick={() => setPage(p => Math.max(0, p - 1))}
            disabled={page === 0}
            className="p-1.5 rounded bg-white/5 hover:bg-white/10 text-secondary disabled:opacity-30 transition-colors"
          >
            <ChevronLeft size={14} />
          </button>
          <button
            onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))}
            disabled={page >= totalPages - 1}
            className="p-1.5 rounded bg-white/5 hover:bg-white/10 text-secondary disabled:opacity-30 transition-colors"
          >
            <ChevronRight size={14} />
          </button>
        </div>
      </div>
    </div>
  );
}
