/**
 * ArtifactsPage
 *
 * Full-page artifact browser with stats, filtering, and search.
 */

import { useEffect } from 'react';
import {
  Package,
  Pin,
  Sparkles,
  Loader2,
} from 'lucide-react';
import { GlassContainer } from '@/components/primitives/GlassContainer';
import { GlassArtifactExplorer } from '@/components/artifacts/GlassArtifactExplorer';
import { useArtifactStore } from '@/stores/artifactStore';

export function ArtifactsPage() {
  const {
    recentArtifacts,
    pinnedArtifactIds,
    fetchRecentArtifacts,
    isLoading,
  } = useArtifactStore();

  useEffect(() => {
    fetchRecentArtifacts(50);
  }, [fetchRecentArtifacts]);

  const pinnedCount = pinnedArtifactIds.length;
  const totalCount = recentArtifacts.length;

  return (
    <div className="min-h-screen p-8">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
          <Package className="text-purple-400" />
          Artifact Explorer
        </h1>
        <p className="text-white/60">
          Browse and manage artifacts generated by AI agents
        </p>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        <GlassContainer className="p-4" border>
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-purple-500/20">
              <Package className="text-purple-400" size={20} />
            </div>
            <div>
              <p className="text-white/60 text-sm">Total Artifacts</p>
              <p className="text-2xl font-bold text-white">
                {isLoading ? <Loader2 className="animate-spin" size={20} /> : totalCount}
              </p>
            </div>
          </div>
        </GlassContainer>

        <GlassContainer className="p-4" border>
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-amber-500/20">
              <Pin className="text-amber-400" size={20} />
            </div>
            <div>
              <p className="text-white/60 text-sm">Pinned</p>
              <p className="text-2xl font-bold text-white">{pinnedCount}</p>
            </div>
          </div>
        </GlassContainer>

        <GlassContainer className="p-4" border>
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-green-500/20">
              <Sparkles className="text-green-400" size={20} />
            </div>
            <div>
              <p className="text-white/60 text-sm">New Today</p>
              <p className="text-2xl font-bold text-white">
                {recentArtifacts.filter(a => {
                  const today = new Date();
                  const created = new Date(a.createdAt);
                  return created.toDateString() === today.toDateString();
                }).length}
              </p>
            </div>
          </div>
        </GlassContainer>
      </div>

      {/* Artifact Explorer */}
      <GlassArtifactExplorer isOpen={true} className="min-h-[600px]" />
    </div>
  );
}

export default ArtifactsPage;
