import { LiquidSmartComponent } from '../../liquid-engine/react';
import { GlassContainer } from '../primitives/GlassContainer';

/**
 * GlassSmartCard
 * 
 * A generic container that can display content generated by an AI tool.
 * Listens for the 'generate_card' tool.
 */

export function GlassSmartCard() {
    return (
        <LiquidSmartComponent
            name="generate_card"
            render={({ status, args }) => {
                const isLoading = status === 'running';

                return (
                    <GlassContainer className="w-full max-w-md p-6 transition-all duration-300">
                        <div className="flex flex-col space-y-4">
                            {/* Title */}
                            <h3 className={`text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary min-h-[1.75rem] ${isLoading && !args.title ? 'animate-pulse bg-white/10 rounded w-2/3' : ''}`}>
                                {args.title}
                            </h3>

                            {/* Body content */}
                            <div className={`text-gray-300 whitespace-pre-wrap min-h-[4rem] ${isLoading && !args.body ? 'animate-pulse bg-white/5 rounded w-full' : ''}`}>
                                {args.body}
                            </div>

                            {/* Footer */}
                            {args.footer && (
                                <div className="pt-4 mt-2 border-t border-glass-border text-sm text-gray-500">
                                    {args.footer}
                                </div>
                            )}

                            {/* Loading Indicator */}
                            {isLoading && (
                                <div className="absolute top-2 right-2">
                                    <span className="animate-spin inline-block w-4 h-4 border-2 border-primary border-t-transparent rounded-full opacity-50"></span>
                                </div>
                            )}
                        </div>
                    </GlassContainer>
                );
            }}
        />
    );
}
