/**
 * {{appName}} - Dashboard Template
 *
 * Auto-generated by LiquidOS Builder. Replace placeholder data
 * with real data sources and customize components.
 */

import { useState, useEffect } from 'react';
import { LayoutDashboard, RefreshCw, TrendingUp, Activity, BarChart3 } from 'lucide-react';

interface MetricCard {
  label: string;
  value: string;
  change?: string;
  trend?: 'up' | 'down' | 'flat';
  icon: React.ReactNode;
}

export default function App() {
  const [metrics, setMetrics] = useState<MetricCard[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Replace with real data fetching
    setMetrics([
      { label: 'Total Items', value: '1,234', change: '+12%', trend: 'up', icon: <BarChart3 size={18} /> },
      { label: 'Active', value: '567', change: '+5%', trend: 'up', icon: <Activity size={18} /> },
      { label: 'Growth', value: '89%', change: '+2.3%', trend: 'up', icon: <TrendingUp size={18} /> },
    ]);
    setLoading(false);
  }, []);

  return (
    <div className="flex flex-col h-full bg-glass-background">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-4 border-b border-white/10">
        <div className="flex items-center gap-3">
          <LayoutDashboard size={20} className="text-accent" />
          <h1 className="text-lg font-semibold text-primary">{'{{appName}}'}</h1>
        </div>
        <button
          onClick={() => setLoading(true)}
          className="p-2 rounded-lg bg-white/5 hover:bg-white/10 text-secondary hover:text-primary transition-colors"
        >
          <RefreshCw size={16} className={loading ? 'animate-spin' : ''} />
        </button>
      </header>

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 p-6">
        {metrics.map((metric, i) => (
          <div
            key={i}
            className="p-4 rounded-xl bg-glass-surface border border-white/10 backdrop-blur-md"
          >
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs text-secondary">{metric.label}</span>
              <span className="text-accent">{metric.icon}</span>
            </div>
            <div className="text-2xl font-bold text-primary">{metric.value}</div>
            {metric.change && (
              <span className={`text-xs ${metric.trend === 'up' ? 'text-emerald-400' : 'text-red-400'}`}>
                {metric.change}
              </span>
            )}
          </div>
        ))}
      </div>

      {/* Main Content Area */}
      <div className="flex-1 p-6">
        <div className="h-full rounded-xl bg-glass-surface border border-white/10 backdrop-blur-md p-6">
          <h2 className="text-sm font-semibold text-primary mb-4">Dashboard Content</h2>
          <p className="text-xs text-secondary">
            Replace this section with charts, tables, or other data visualizations.
          </p>
        </div>
      </div>
    </div>
  );
}
