import type { Meta, StoryObj } from '@storybook/react';
import { useEffect, useState } from 'react';
import { GlassSmartCard } from './GlassSmartCard';
import { LiquidClient } from '../../liquid-engine/client';
import { LiquidProvider } from '../../liquid-engine/react';
import { GlassButton } from '../primitives/GlassButton';

const meta: Meta<typeof GlassSmartCard> = {
    title: 'Generative/GlassSmartCard',
    component: GlassSmartCard,
    tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof GlassSmartCard>;

// Simulator Component
const Simulator = ({
    data,
    delay = 50,
    autoStart = true
}: {
    data: any,
    delay?: number,
    autoStart?: boolean
}) => {
    const [client] = useState(() => new LiquidClient());
    const [isRunning, setIsRunning] = useState(false);

    const runSimulation = () => {
        if (isRunning) return;
        setIsRunning(true);

        const id = `call-${Date.now()}`;
        const toolName = 'generate_card'; // Must match GlassSmartCard's listener

        // 1. Start
        client.ingest({
            type: 'tool_start',
            id,
            name: toolName
        } as any);

        // 2. Stream content
        const fullContent = JSON.stringify(data);
        let currentIndex = 0;
        const chunkSize = 5;

        const interval = setInterval(() => {
            if (currentIndex >= fullContent.length) {
                // 3. Complete
                clearInterval(interval);
                client.ingest({
                    type: 'tool_complete',
                    id,
                    name: toolName,
                    result: { success: true }
                } as any);
                setIsRunning(false);
                return;
            }

            const delta = fullContent.slice(currentIndex, currentIndex + chunkSize);
            client.ingest({
                type: 'tool_delta',
                id,
                name: toolName,
                delta
            } as any);

            currentIndex += chunkSize;
        }, delay);
    };

    useEffect(() => {
        if (autoStart) {
            setTimeout(runSimulation, 500);
        }
    }, []);

    return (
        <LiquidProvider client={client}>
            <div className="flex flex-col gap-8 items-start">
                <GlassSmartCard />

                <GlassButton onClick={runSimulation} disabled={isRunning} size="sm">
                    {isRunning ? 'Streaming...' : 'Re-Generate AI Response'}
                </GlassButton>
            </div>
        </LiquidProvider>
    );
};

export const MarketSummary: Story = {
    render: () => (
        <Simulator
            data={{
                title: "Bitcoin Market Update",
                body: "BTC has broken the $65k resistance level with strong trading volume.\n\nInstitutional inflows remain positive for the 5th consecutive week, suggesting sustained bullish momentum.",
                footer: "Generated by Strategy Agent • Just now"
            }}
        />
    )
};

export const TradeSignal: Story = {
    render: () => (
        <Simulator
            data={{
                title: "New Signal: ETH/USDT",
                body: "Entry Zone: $3,450 - $3,480\nTarget 1: $3,600\nTarget 2: $3,800\nStop Loss: $3,350\n\nThe price action shows a classic cup and handle formation on the 4H timeframe.",
                footer: "Confidence Score: 85%"
            }}
        />
    )
};
